service: quiztopia-examination
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: in-examination
  region: eu-north-1
  iam:
    role: arn:aws:iam::861123931289:role/quiztopia-examination
  deploymentMethod: direct
  stage: api

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: 'webpack.config.cjs'

functions:
  registerUser:
    handler: src/functions/auth/registerUser.handler
    events:
      - http:
          path: /auth/register
          method: POST
  loginUser:
    handler: src/functions/auth/loginUser.handler
    events:
      - http:
          path: /auth/login
          method: POST
  createQuiz:
    handler: src/functions/quiz/createQuiz.handler
    events:
      - http:
          path: /quiz
          method: POST
  getQuizzes:
    handler: src/functions/quiz/getQuizzes.handler
    events:
      - http:
          path: /quiz
          method: GET
  getQuiz:
    handler: src/functions/quiz/getQuiz.handler
    events:
      - http:
          path: /quiz/{quizId}
          method: GET
  deleteQuiz:
    handler: src/functions/quiz/deleteQuiz.handler
    events:
      - http:
          path: /quiz/{quizId}
          method: DELETE
  addQuestionToQuiz:
    handler: src/functions/quiz/addQuestionToQuiz.handler
    events:
      - http:
          path: /quiz/{quizId}/addQuestion
          method: POST
  addPointsToUser:
    handler: src/functions/quiz/addPointsToUser.handler
    events:
      - http:
          path: /quiz/{quizId}/addpoints
          method: POST
  leaderBoardForQuiz:
    handler: src/functions/quiz/leaderboard.handler
    events:
      - http:
          path: /quiz/{quizId}/leaderboard 
          method: GET

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    QuizzesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Quizzes
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
        KeySchema:
            - AttributeName: quizId
              KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    QuestionsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Questions
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: questionId
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
          - AttributeName: questionId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    LeaderboardTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Leaderboard
        AttributeDefinitions:
          - AttributeName: leaderboardId
            AttributeType: S
          - AttributeName: user
            AttributeType: S
        KeySchema:
          - AttributeName: leaderboardId
            KeyType: HASH
          - AttributeName: user
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: UserIndex
            KeySchema:
              - AttributeName: user
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST